[workspace]
resolver = "2"
members = ["common", "api/server", "client/agent", "client/app", "client/capture", "client/recorder", "client/storage", "client/ops"]

[workspace.package]
edition = "2021"
version = "0.3.53"
license = "GPL-3.0-or-later"
repository = "https://github.com/GavaOfficial/Relay"
