[package]
name = "relay-vk-layer"
version.workspace = true
edition.workspace = true
license.workspace = true
[lib]
crate-type = ["cdylib"]
[target.'cfg(windows)'.dependencies]
ash = "0.38"
anyhow = "1"
relay-hook-protocol = { path = "../protocol" }
relay-hook-gpu = { path = "../hook-gpu" }
windows = { version = "0.62", features = ["Win32_Graphics_Direct3D11", "Win32_Graphics_Dxgi"] }
windows-sys = { version = "0.61", features = ["Win32_System_Threading"] }
